# Generated by Django 4.1.6 on 2023-04-02 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_pokerpalssessions_big_blind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_pakerspals',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usersessions',
            name='added_chips',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='usersessions',
            name='end_roll',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='usersessions',
            name='start_roll',
            field=models.FloatField(),
        ),
    ]
