# Generated by Django 4.1.6 on 2023-04-02 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_profile_is_pakerspals_alter_usersessions_added_chips_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_pakerspals',
            new_name='ispokerpals',
        ),
    ]
