# Generated by Django 4.1.6 on 2023-04-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_is_pakerspals_profile_ispokerpals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokerpalssessions',
            name='time_delta',
            field=models.FloatField(),
        ),
    ]
